apiVersion: v1
kind: Service
metadata:
  name: dotnetapi-service
spec:
  selector:
    app: dotnetapi
  ports:
    - protocol: TCP
      port: 80       # Exposing port 80
      targetPort: 3000  # Application runs on port 3000 inside the container
  type: ClusterIP

